server:
  port: 5000

spring:
  jpa:
    hibernate:
      ddlAuto: update
  thymeleaf:
    checkTemplateLocation: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
