server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://delimo.rds.amazonaws:3306/delimo
    username: admin
    password: Sh
    driverClassName: com.mysql.cj.jdbc.Driver
    show-sql: true
  resources:
    add-mappings: true

  jpa:
    hibernate:
      ddlAuto: none
  thymeleaf:
    checkTemplateLocation: false
