spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  hello:
    javax:
      persistence:
        jdbc:
          driver: org.h2.Driver
          user: sa
          password:
          url: jdbc:h2:tcp://localhost/~/test

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace